modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/mcNETDev/hgtools/issues"
license = "All Rights Reserved"

[[mods]]
modId = "hgtools"
version = "${file.jarVersion}"
displayName = "HGTools"
authors = "mcNETDev"
description = '''
A mod that add some usefull commands!
'''

[[dependencies.hgtools]]
modId="forge"
mandatory = true
versionRange = "[32,)"
ordering = "NONE"
side="BOTH"

[[dependencies.hgtools]]
modId="minecraft"
mandatory = true
versionRange = "[1.16,)"
ordering = "NONE"
side="BOTH"